apps/courses/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^add/$', views.add_course, name='add'),
    url(r'^destroy/(?P<id>\d+)$', views.destroy, name='destroy'),
    url(r'^confirm/(?P<id>\d+)$', views.confirm_destroy, name='confirm_destroy'),
    url(r'^users_courses/$', views.users_courses, name='users_courses'),
    url(r'^users_courses/add_user/$', views.add_user, name='add_user_to_course')
]

integration_project/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^', include('apps.loginreg.urls', namespace='user')),
    url(r'^courses/', include('apps.courses.urls', namespace='courses'))
]

apps/courses/models.py
from __future__ import unicode_literals
from django.db import models
from ..loginreg.models import User

class CourseManager(models.Manager):
    def add_course(self, form_data):
        print("validating new course")
        errors = []
        # Check for empty course name
        if len(form_data['name']) == 0:
            errors.append("Invalid Course Name")
        courses = Course.objects.filter(name=form_data['name'])
        if courses:
            errors.append("Course has already been added to database")

        if len(errors) is not 0:
            print("Failed course validations")
            return (False, errors)
        else:
            print("Passed validations. Adding course to database")
            course = Course.objects.create(name=form_data['name'], description=form_data['description'])
            return (True, course)

# Create your models here.
class Course(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    users = models.ManyToManyField(User)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = CourseManager()

apps/courses/views.py
from django.shortcuts import render, redirect
from .models import Course
from ..loginreg.models import User
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.db.models import Count

# Create your views here.
def index(request):
    context = {
        'courses': Course.objects.all().order_by('name')
    }
    return render(request, 'courses/index.html', context)

def add_course(request):
    if request.method == 'POST':
        validation = Course.objects.add_course(request.POST)
        if validation[0]:
            return redirect(reverse('courses:index'))
        else:
            messages.error(request, validation[1])
    return redirect('/courses')

def destroy(request, id):
    #Course.objects.get(id=id).delete()
    context = {
        'course': Course.objects.get(id=id)
    }
    return render(request, 'courses/delete.html', context)
def confirm_destroy(request, id):
    Course.objects.get(id=id).delete()
    return redirect('/courses')

def users_courses(request):
    courses = Course.objects.annotate(number_of_users=Count('users')).order_by('name')
    context = {
        'courses': courses,
        'users': User.objects.all().order_by('id')
    }
    return render(request, 'courses/users_courses.html', context)

def add_user(request):
    if request.method == 'POST':
        course = Course.objects.get(id=request.POST['course'])
        print(course)
        user = User.objects.get(id=request.POST['user'])
        print(user)
        course.users.add(user)
    return redirect(reverse('courses:users_courses'))

apps/courses/templates/courses/delete.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Delete Course</title>
        {% load staticfiles %}
        <link rel="stylesheet" href="{% static 'courses/css/styles.css' %}"media="screen" title="no title"  charset="utf-8">
    </head>
    <body>
        <h1>Are you sure you want to delete the following course?</h1>
        <p>Name: {{course.name}}</p>
        <p>Description: {{course.description}}</p>
        <a href="/courses"><button type="button" name="no">No</button></a>
        <a href="{% url 'courses:confirm_destroy' id=course.id %}"><button type="button" name="Delete">Yes! I want to delete this</button></a>
    </body>
</html>

apps/courses/templates/courses/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Courses</title>
        {% load staticfiles %}
        <link rel="stylesheet" href="{% static 'courses/css/styles.css' %}"media="screen" title="no title"  charset="utf-8">
    </head>
    <body>
        <h3>Add a new course</h3>
        <form action="{% url 'courses:add' %}" method="post">
            {% csrf_token %}
            Name: <input type="text" name="name" value="">
            Description: <textarea name="description" rows="8" cols="40"></textarea>
            <input type="submit" name="submit" value="Add">
        </form>
        {% if messages %}
            <ul class='messages'>
                {% for message in messages %}
                    <li{%if message.tags %} class="{{message.tags}}" {% endif %}>{{message}}</li>
                {% endfor %}
            </ul>
        {% endif %}
        <h2>Courses</h2>
        <table>
            <tr class='row1'>
                <th>Course Name</th>
                <th>Description</th>
                <th>Date Added</th>
                <th>Action</th>
            </tr>
            {% for course in courses %}
                <tr class="{% cycle 'row2' 'row1' %}">
                    <th>{{course.name}}</th>
                    <th>{{course.description}}</th>
                    <th>{{course.created_at}}</th>
                    <th><a href="{% url 'courses:destroy' id=course.id %}">Remove</a></th>
                </tr>
            {% endfor %}
        </table>
    </body>
</html>

apps/courses/templates/courses/users_courses.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Users Courses Table</title>{% load staticfiles %}
        <link rel="stylesheet" href="{% static 'courses/css/styles.css' %}"media="screen" title="no title"  charset="utf-8">
    </head>
    <body>
        <form class="" action="{% url 'courses:add_user_to_course' %}" method="post">
            {% csrf_token %}
            <select class="" name="user">
                <option value="" disabled selected>Users</option>
                {% for user in users %}
                    <option value="{{user.id}}">{{user.first_name}} {{user.last_name}} - {{user.email}}</option>
                {% endfor %}
            </select>
            <select class="" name="course">
                <option value="" disabled selected>Courses</option>
                {% for course in courses %}
                    <option value="{{course.id}}">{{course.name}}</option>
                {% endfor %}
            </select>
            <input type="submit" name="name" value="Add User To Course">
        </form>
        <table>
            <tr class='row1'>
                <th>Course Name</th>
                <th>Description</th>
                <th>Number of users</th>
            </tr>
            {% for course in courses %}
                <tr class="{% cycle 'row2' 'row1' %}">
                    <th>{{course.name}}</th>
                    <th>{{course.description}}</th>
                    <th>{{course.number_of_users}}</th>
                </tr>
            {% endfor %}
        </table>
    </body>
</html>