apps/loginreg/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.login, name='login'),
    url(r'^register/$', views.register, name='register'),
    url(r'^success/$', views.success, name='success'),
    url(r'^logout/$', views.logout, name='logout')
]

integration_project/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^', include('apps.loginreg.urls', namespace='user')),
    url(r'^courses/', include('apps.courses.urls', namespace='courses'))
]

apps/loginreg/models.py
from __future__ import unicode_literals
from django.db import models
import bcrypt

import re
email_regex = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')
#found a name regex from online
name_regex = re.compile(r'^[A-Z][-a-zA-Z]+$')

# Create your models here.
class UserManager(models.Manager):
    def login(self, form_data):
        print("Validating login")
        # retrieve the user from database using email
        user = User.objects.filter(email=form_data['email'])
        if user:
            print('User found in database')
            user = user[0]
            if bcrypt.checkpw(form_data['pw'].encode(), user.pw_hash.encode()):
                print("passwords match")
                # returning user object to views
                return (True, user)
        return (False, "Invalid email or password")

    def register(self, form_data):
        # Validation portion. Pushes all errors to an array that is returned if there are errors
        errors = []
        if not name_regex.match(form_data['first_name']) or not name_regex.match(form_data['last_name']):
            errors.append("Invalid first or last name")
        if not email_regex.match(form_data['email']):
            errors.append("Invalid Email")
        if len(form_data['pw']) < 8:
            errors.append("Password must be 8 or more characters in length")
        if form_data['pw'] != form_data['pw_confirmation']:
            errors.append("Password must match password confirmation")
        user = User.objects.filter(email=form_data['email'])
        if user:
            errors.append("Email has already been used")
        # checks if there were any errors
        if len(errors) is not 0:
            return (False, errors)
        else:
            print("passed validations")
            # create the hashed password using bcrypt. Remember to encode
            pw_hash = bcrypt.hashpw(form_data['pw'].encode(), bcrypt.gensalt().encode())
            # create() method in objects returns newly entered entry in your db
            user = User.objects.create(email=form_data['email'], first_name=form_data['first_name'], last_name=form_data['last_name'], pw_hash=pw_hash)
            return (True, user)

# Create your models here.
class User(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    pw_hash = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = UserManager()

apps/loginreg/views.py
from django.shortcuts import render, redirect
from .models import User
from django.contrib import messages
from django.core.urlresolvers import reverse

# Create your views here.
def index(request):
    if 'user_id' in request.session:
        return redirect('/success')
    else:
        return render(request, 'loginreg/index.html')

def login(request):
    if request.method == 'POST':
        validation = User.objects.login(request.POST)
        if validation[0]:
            return log_user_in(request, validation[1])
        else:
            messages.error(request, validation[1])
            return redirect('/')
    else:
        return redirect('/')

def register(request):
    if request.method == 'POST':
        validation = User.objects.register(request.POST)
        #check if registration validation returns true
        if validation[0]:
            return log_user_in(request, validation[1])
        else:
            for error in validation[1]:
                # add errors to flash messages
                messages.error(request, error)
            return redirect('/')
    else:
        return redirect('/')

def success(request):
    if 'user_id' not in request.session:
        messages.error(request, "You are not logged in")
        return redirect('/')
    else:
        context = {
            'users': User.objects.all()
        }
        return render(request, 'loginreg/success.html', context)

def log_user_in(request, user):
    print("running log_user_in function")
    request.session['user_id'] = user.id
    # add user to success flash message
    messages.success(request, "Welcome, {} {}. You are logged in.".format(user.first_name, user.last_name))
    return redirect('/success')

def logout(request):
    del request.session['user_id']
    return redirect('/')

apps/loginreg/templates/loginreg/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Login and Registration</title>
        {% load staticfiles %}
        <link rel="stylesheet" href="{% static 'loginreg/css/styles.css' %}"media="screen" title="no title"  charset="utf-8">
    </head>
    <body>
        <h1>Login</h1>
        <form action="{% url 'user:login' %}" method="post">
            {% csrf_token %}
            <input type="text" name="email" value="" placeholder="Email">
            <input type="text" name="pw" value="" placeholder="Password">
            <input type="submit" name="name" value="Login">
        </form>
        <h1>Registration</h1>
        {% if messages %}
            <ul class='messages'>
                {% for message in messages %}
                    <li{%if message.tags %} class="{{message.tags}}" {% endif %}>{{message}}</li>
                {% endfor %}
            </ul>
        {% endif %}
        <form action="{% url 'user:register' %}" method="post">
            {% csrf_token %}
            <input type="text" name="first_name" value="" placeholder="First name">
            <input type="text" name="last_name" value="" placeholder="Last name">
            <input type="text" name="email" value="" placeholder="email">
            <input type="text" name="pw" value="" placeholder="password">
            <input type="text" name="pw_confirmation" value="" placeholder="password confirmation">
            <input type="submit" name="name" value="Register">
        </form>
    </body>
</html>

apps/loginreg/templates/loginreg/success.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Success</title>
        {% load staticfiles %}
        <link rel="stylesheet" href="{% static 'loginreg/css/styles.css' %}"media="screen" title="no title"  charset="utf-8">
    </head>
    <body>
        {% if messages %}
            <ul class='messages'>
                {% for message in messages %}
                    <li{%if message.tags %} class="{{message.tags}}" {% endif %}> {{message}}</li>
                {% endfor %}
            </ul>
        {% endif %}
        <a href="/logout">Logout</a>
        <h2>Users in Database:</h2>
        {% if users %}
            <ul>
                {% for user in users %}
                    <li>{{user.first_name}} {{user.email}} {{Created_at}}</li>
                {% endfor %}
            </ul>
        {% endif %}
    </body>
</html>